### ISSUE TITLE
Game does not launch with Create: Destroy addon on the latest version.

### ISSUE THREAD

**Issue by water-mizuu** [Sinytra/ForgifiedFabricAPI#115]
### Describe the bug

The log describes a mixin failure with fabric-item-api apparently, which only appeared in the latest version of the API.

### Steps to reproduce

1. Install Connector and its family of mods
2. Install Create 0.5.1f and the Destroy addon 0.8

### Logs

https://gist.github.com/water-mizuu/e08dec8271b03940abafca2c3547e584

### Additional context

This did not happen before the latest update.

**Comment by unilock** [comment]
The problem stems from Destroy completely `@Overwrite`ing `ClientPlayerInteractionManager#isCurrentlyBreaking` / `MultiPlayerGameMode#sameDestroyTarget`:  
https://github.com/petrolpark/Destroy/blob/7d91768bf5d55c2ba399115269ef877f9cf76144/src/main/java/com/petrolpark/destroy/mixin/MultiPlayerGameModeMixin.java#L16-L26

Apparently, Destroy has this workaround because Forge's own implementation of `FabricItem#allowContinuingBlockBreaking` (that being `IForgeItem#shouldCauseBlockBreakReset`) doesn't actually work? (https://github.com/petrolpark/Destroy/issues/37, https://github.com/neoforged/NeoForge/issues/143)  
That oversight was, however, fixed in NeoForge: https://github.com/neoforged/NeoForge/pull/145

**Comment by water-mizuu** [comment]
So, the solution is to use NeoForge instead of Forge?

**Comment by Su5eD** [comment]
No, the solution is to update to 0.92.1+1.11.7+1.20.1 :)
