### ISSUE TITLE
Incompatible with rubidium

### ISSUE THREAD

**Issue by kakashi1464** [Sinytra/ForgifiedFabricAPI#22]
### Describe the bug

Minecraft crashes at start with FFAPI and Rubidium

### Steps to reproduce

1.Add rubidium and FFAPI in mods folder
2.Run Minecraft

### Logs

https://mclo.gs/SbkMplt

**Comment by burningtnt** [comment]
> ### Describe the bug
> Minecraft crashes at start with FFAPI and Rubidium
> 
> ### Steps to reproduce
> 1.Add rubidium and FFAPI in mods folder 2.Run Minecraft
> 
> ### Logs
> https://mclo.gs/SbkMplt
> 
> ### Additional context
> _No response_

No crash info available. Please export the output of Minecraft through you Minecraft Launcher instead of uploading latest.log

**Comment by Su5eD** [comment]
Rubidium 0.7.0a works fine with the Forgified Fabric API.

Rubidium 0.6.5 crashes due to a package conflict, where rubidium includes classes from fabric loader without relocating them. It looks like they're only using the version util classes though, so I'm not sure what prevented them from shadowing properly. We cannot relocate our classes, as they are expected to be available by dependents.

**Comment by kakashi1464** [comment]
sad situation
