### ISSUE TITLE
Crash with CreativeCore

### ISSUE THREAD

**Issue by Starexify** [Sinytra/ForgifiedFabricAPI#37]
### Describe the bug

Trying to run CreativeCore with Forgified Fabric API crashing game.

### Steps to reproduce

1. Install CreativeCore v2.10.34 Forge, and Forgified Fabric API 1.9.8 .
2. Run the game.
3. Crash without crashlog.

### Logs

https://pastebin.com/spiGmDVK

### Additional context

I will report other mods if I find that crash and hope we can get as many fixes as possible ! 
I love the mod very much but bugs like this are making it sadly unusable xD

**Comment by Su5eD** [comment]
As described in #22, this is a rather troublesome issue to fix in FFAPI. Creative Core crashes due to a split package conflict caused by both mods including classes from fabric loader without relocating them. We cannot easily relocate our classes, as they are expected to be available by dependent mods to the full extent (just like on fabric).

If you're using Connector, its mod locator service will be able to fix this issue in the next release.

**Comment by MrKashew** [comment]
to clarify - this means Connector will be able to run CreativeCore together w FFAPI?

**Comment by CreativeMD** [comment]
You can open the CreativeCore jar file and delete the `net` folder. There is no other way to solve this issue because CreativeCore and Forgified Fabric API do the same thing. CreativeCore also acts as a universal loader so that mods like ItemPhysic, EnhancedVisuals, AmbientSounds work on both Fabric and Forge. It only includes a very limited amount of fabric classes, but it is already enough to break everything.

**Comment by CreativeMD** [comment]
Actually the newest version of CreativeCore should work with this mod.
