### ISSUE TITLE
Made a report for Diagnal Fences/Windows but they said it was your mod

### ISSUE THREAD

**Issue by Camawama** [Sinytra/ForgifiedFabricAPI#76]
### Describe the bug

Crash

### Steps to reproduce

https://github.com/Fuzss/diagonalfences/issues/6

**Comment by Su5eD** [comment]
This is a mixin conflict with [Valhesia Core](https://www.curseforge.com/minecraft/mc-mods/valhelsia-core). However, for some reason the mod is closed source, so I don't know what exactly they're doing. It would be good to make them aware of the issue as well.

Since Mixin doesn't support chaining `@Redirect` injectors, the only viable option would be switching to [`@WrapOperation`](https://github.com/LlamaLad7/MixinExtras/wiki/WrapOperation) provided by Mixin Extras. However, in order for that to work, both mods must apply the change. I'm completely fine with using it in FFAPI, so it's up to Valhesia core's devs.
